version: '3'

services:
  node-exporter:
    image: prom/node-exporter
    ports:
    - '9100:9100'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100M'
        reservations:
          cpus: '0.1'
          memory: '50M'
  cadvisor-exporter:
    image: google/cadvisor
    ports:
    - "9200:8080"
    privileged: true
    volumes:
    - /:/rootfs:ro
    - /cgroup:/cgroup:ro
    - /var/run:/var/run:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    - /cgroup:/sys/fs/cgroup:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100M'
        reservations:
          cpus: '0.1'
          memory: '50M'

